packages/apps/nft-data/src/components/nftTabs/JSONTab.tsx
• FIXED JSON view without installing packages
=> Dap 231 bug format json view

packages/features/sales-escrows/pages/NFTPage/index.tsx
=> Dap 275 update nft details

packages/apps/wallet/src/pages/Wallet/Filter.tsx, packages/apps/wallet/src/pages/Wallet/index.tsx
=> added SearchBar + function

.npmrc, packages/apps/library/src/components/AddLibrary/canister_location.tsx, packages/apps/library/src/components/AddLibrary/collection_location.tsx, packages/apps/library/src/components/AddLibrary/web_location.tsx, packages/apps/library/src/components/DeleteLibrary/index.tsx, packages/apps/library/src/components/LibraryBox/index.tsx, packages/apps/library/src/components/NFTLibrary/index.tsx, packages/apps/library/src/pages/Login/index.tsx, packages/features/components/src/SearchbarNft/index.tsx
=> UI updates

packages/apps/wallet/src/pages/Wallet/index.tsx, packages/features/sales-escrows/modals/ManageEscrows.tsx, packages/features/sales-escrows/modals/StartAuctionModal.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx
- on Vault page, the Status price of current bidding was displaying like 2750000 instead of 2.75 OGY
- on NFT Page, when starting Auction, it the loading modal was 'Transfer in Progress' not Starting an Auction in Progress'
=> fixed Status tokens

packages/apps/library/src/components/UpdateLibrary/UpdateLibraryFile.tsx
- Changed max file size to 2 GB in the DropZone component to prevent error message about file size.
- Added 5 retries for the file upload.
- Added 5 retries for the metadata update.
- Added message above progress bar when library is updating.
- Some code refactoring for better error handling.
- Some reformatting from prettier.
=> ENG-1080 Fixes for update library

packages/apps/marketplace/src/App.tsx, packages/apps/marketplace/src/components/context/index.tsx, packages/apps/marketplace/src/components/context/types.tsx, packages/apps/marketplace/src/index.tsx, packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/apps/wallet/src/pages/Wallet/Filter.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx
- Added marketplace context provider to lift state so the main page can load quickly when navigating back.
- Updated Filter/Sort component to load initial filter/sort values passed as args.
- Values from context are passed in to restore drop-down selections when navigating back.
- Added TypeScript interfaces.
- Fixed filtering and sorting.
- Refactored code to flatten nested structures and use async/await in place of promise callbacks.
- Renamed "NFT" to "Digital Certificate" or "ODC" (Origyn Digital Certificate) in all forms.
- Removed dead code.
=> ENG-1088 Marketplace bug fixes

packages/features/sales-escrows/pages/NFTPage/index.tsx
fixed how the royalties are displayed, primary and secondary
=> fixed royalties details

packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx
it displays the buy Now price if the current bid is 0
=> Fixed buy now status

packages/features/sales-escrows/pages/NFTPage/index.tsx
- added Finish Sale button to ended Sale so that onwer is able to reset the sale an put the NFT for sale again
=> ENG-1125-fix-end-sale

packages/apps/library/src/components/LayoutsType/LibraryImage/index.tsx
Height 70vh was causing image squishing
=> ENG-1089-Fix/preview-Image-squishing

package-lock.json, packages/apps/nft-data/src/pages/NFTInfo/index.tsx, packages/candy_editor/src/assets/formTypes/NatForms/converters.ts, packages/candy_editor/src/assets/formTypes/NatForms/nat16Form.tsx, packages/candy_editor/src/assets/formTypes/NatForms/nat32Form.tsx, packages/candy_editor/src/assets/formTypes/NatForms/nat64Form.tsx, packages/candy_editor/src/assets/formTypes/NatForms/nat8Form.tsx, packages/candy_editor/src/assets/formTypes/NatForms/natForm.tsx, packages/candy_editor/src/assets/formTypes/index.tsx, packages/candy_editor/src/assets/formTypes/textForm.tsx, packages/candy_editor/src/assets/index.tsx, packages/candy_editor/src/constants.ts, packages/candy_editor/src/tests/converters.test.js
> Added components in formTypes > NatForms for the creation of these CandyType: 
- CandyNat
- CandyNat8
- CandyNat16
- CandyNat32
- CandyNat64
> Created the file converter.ts in NatForms folder , it contains all the functions to convert the typedValue to the specific CandyType
> Added the array SELECT_OPTIONS to the file constants.ts
> Added the object  VALIDATION_ERRORS to the file constants.ts, it stores all the errors to display when the user enter an invalid CandyType
=> ENG-1134 Components for Nat, Nat8,16,32,64 types

packages/candy_editor/src/assets/formTypes/BoolForm/boolForm.tsx, packages/candy_editor/src/assets/formTypes/BoolForm/boolsForm.tsx, packages/candy_editor/src/assets/formTypes/BoolForm/converters.ts, packages/candy_editor/src/assets/formTypes/IntForms/converters.ts, packages/candy_editor/src/assets/formTypes/IntForms/integersForm.tsx, packages/candy_editor/src/assets/formTypes/NatForms/converters.ts, packages/candy_editor/src/assets/formTypes/NatForms/naturalsForm.tsx, packages/candy_editor/src/assets/formTypes/index.tsx, packages/candy_editor/src/constants.ts, packages/candy_editor/src/tests/converters.test.js
- Added BoolForm > boolsForm.tsx 
- Added BoolForm > converters.ts - function to check if the passed string is a valid bool value, if it is, it return a CandyBool type 
- Added  BOOLEAN to the Array constants.ts > VALIDATION_ERRORS 
- Added bool to constants.ts > SELECT_OPTIONS 
- Updated the formtypes > index.tsx with the new BoolsForm layout
- Added unit test for BoolForm > converters.ts
=> ENG-1136 BoolForm

packages/apps/wallet/src/pages/Wallet/index.tsx
- added a button to get teh user from the Vault NFT collection view to the Ledger to see the NFT history
=> ENG-558 add ledger href

packages/apps/MintingB2B/src/constants/minting.ts, packages/apps/MintingB2B/src/pages/NFTDetails/index.tsx
- Add keys to every map.
- Add a function to download every file after minting.
- Add a map function to generate a card with a download button to download the specific file.
=> ENG-1101 User Be Able To Download Documents After Mint

packages/candy_editor/src/assets/formTypes/FloatForm/converters.ts, packages/candy_editor/src/assets/formTypes/FloatForm/floatForm.tsx, packages/candy_editor/src/assets/formTypes/IntForms/integersForm.tsx, packages/candy_editor/src/assets/formTypes/NatForms/naturalsForm.tsx, packages/candy_editor/src/assets/formTypes/PrincipalForm/converters.ts, packages/candy_editor/src/assets/formTypes/PrincipalForm/principalForm.tsx, packages/candy_editor/src/assets/formTypes/index.tsx, packages/candy_editor/src/constants.ts, packages/candy_editor/src/tests/converters.test.js
**FLOAT FORM**
- Added component floatForm.tsx
- Added FloatForm > converter.ts 
- Updated constants.ts
- wrote unit tests for FloatForm > converter.ts > convertToCandyFloat()
- updated formTypes > index.tsx
**PRINCIPAL FORM**
- Added component principalForm.tsx
- Added principalForm > converter.ts 
- Updated constants.ts
- wrote unit tests for PrincipalForm > converter.ts > convertToPrincipal()
- updated formTypes > index.tsx
=> Eng 1137/38 candy data editor candy float/candy principal components

packages/apps/marketplace/src/components/context/types.tsx, packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/features/sales-escrows/modals/ManageDepositsModal.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx
=> ENG-1293 fix offers

packages/apps/library/src/components/AddLibrary/collection_location.tsx, packages/apps/library/src/components/UpdateLibrary/UpdateLibraryCollection.tsx, packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/apps/nft-data/src/components/nftTabs/data/data.ts, packages/apps/nft-data/src/components/nftTabs/inputs/Asset.tsx, packages/apps/wallet/src/pages/Wallet/index.tsx, packages/features/components/src/Layout/index.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx
The issue was caused by the wrong arguments in getInstance()
=> Eng 1294 preview images not loading

packages/features/tokens-provider/src/TokensContextProvider.tsx
- removed tokens form standard tokens
=> ENG-1303-remove XTT WICP

packages/apps/nft-data/src/components/nftTabs/FormTab.tsx, packages/apps/nft-data/src/components/nftTabs/TreeTab.tsx
• Added System in the treeView and formView
• Removed <br /> from formView, replaced with HR and its properties marginbottom - margintop
=> Eng-1318 data dapp is not showing system

packages/utils/src/checkOwner.ts
The Array with managers is stored in the first index of managers. 
`metadataCollectionLevelResponse.ok?.managers --> metadataCollectionLevelResponse.ok?.managers[0]`
=> ENG-1322 Update checkOwner.ts

packages/apps/wallet/src/pages/Wallet/index.tsx
=> ENG-1306 fix offer

packages/apps/nft-data/src/components/nftTabs/Write.tsx, packages/apps/nft-data/src/components/nftTabs/types/origyn_nft_reference.did.d.ts, packages/candy_editor/src/assets/formTypes/BoolForm/boolForm.tsx, packages/candy_editor/src/assets/formTypes/FloatForm/floatForm.tsx, packages/candy_editor/src/assets/formTypes/IntForms/integersForm.tsx, packages/candy_editor/src/assets/formTypes/NatForms/naturalsForm.tsx, packages/candy_editor/src/assets/formTypes/PrincipalForm/principalForm.tsx, packages/candy_editor/src/assets/formTypes/TextForm/textForm.tsx, packages/candy_editor/src/assets/index.tsx, packages/candy_editor/src/constants.ts, packages/candy_editor/src/types/index.ts
• types > index.ts - added the interface 
```
export interface CandyDataEditorProps {
existingCandyClass?: CandyClass;
readOnly?: boolean;
}
```
• constants.ts - added MESSAGES 
• index.tsx - added the logic for Read Only mode and the display of the existing CandyClass
=> ENG-1141 read only mode

packages/candy_editor/src/assets/formTypes/BoolForm/boolForm.tsx, packages/candy_editor/src/assets/formTypes/FloatForm/floatForm.tsx, packages/candy_editor/src/assets/formTypes/IntForms/integersForm.tsx, packages/candy_editor/src/assets/formTypes/NatForms/naturalsForm.tsx, packages/candy_editor/src/assets/formTypes/PrincipalForm/principalForm.tsx, packages/candy_editor/src/assets/formTypes/TextForm/textForm.tsx, packages/candy_editor/src/assets/index.tsx
=> ENG-1324 show candy type

packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx, packages/utils/src/interfaces.ts, packages/utils/src/odcParser.ts
- Partial refactoring of modal to get functionality working
=> Eng 1400 refactor StartEscrowModal

packages/apps/marketplace/webpack.config.js, packages/features/sales-escrows/modals/ManageEscrows.tsx, packages/features/sales-escrows/pages/NFTPage/index.tsx, packages/features/tokens-provider/src/TokensContextProvider.tsx
=> ENG-1400 Small Fixes

packages/features/sales-escrows/modals/ManageEscrows.tsx
• Small refactoring 
• Added the width for Manage Escrows Modal Buyer Side 
• Fixed the use of Flex from UI lib
📸
=> Eng-1428 bug fixes test fix repeat

packages/features/sales-escrows/pages/NFTPage/components/OffersPanel.tsx
=> Eng-1428 prompt to withdraw

packages/utils/src/odcParser.ts
- Fixed null reference for app data properties preventing marketplace from loading.
=> ENG-1466 Fix marketplace loading error

packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/features/sales-escrows/modals/bidsReceivedTab.tsx, packages/features/sales-escrows/modals/bidsSentTab.tsx, packages/features/sales-escrows/modals/offersReceivedTab.tsx, packages/features/sales-escrows/modals/offersSentTab.tsx
_• fixed the StartEscrowModal close._
=> ENG-1448 modal close

packages/features/sales-escrows/modals/ConfirmSalesActionModal.tsx, packages/features/sales-escrows/modals/ManageEscrows.tsx, packages/features/sales-escrows/modals/bidsReceivedTab.tsx, packages/features/sales-escrows/modals/bidsSentTab.tsx, packages/features/sales-escrows/modals/offersReceivedTab.tsx, packages/features/sales-escrows/modals/offersSentTab.tsx
This Pull request contains the refactoring required to solve the bug.
=> Eng-1449 auto refresh balance

packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/utils/src/number.ts
- Fixed float division issue that results in numbers like 899999.9999999999.
- Fixed total in escrow modal when making offers/bids.
- Fixed width of NFT images in marketplace index page.
=> ENG-1450 Float Division

package-lock.json, package.json, packages/features/sales-escrows/modals/StartAuctionModal.tsx, packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/utils/src/number.ts
- Fixed floating arithmetic from adding a currency and fee.
- Fixed floating arithmetic error in start auction and offers/bids.
=> ENG-1450 Floating Arithmetic Fixes

packages/features/sales-escrows/modals/offersReceivedTab.tsx
• In the Modal Escrows > OffersReceived disabled the `ACCEPT` button if you are not the NFT Owner. 
📸
=> Eng-1489 offers received showing wrong nfts

packages/features/sales-escrows/modals/bidsReceivedTab.tsx, packages/features/sales-escrows/modals/bidsSentTab.tsx
Fixed BidSent modal - BidReceived modal .
=> ENG-1484 withdraw offer done

packages/apps/library/package.json, packages/apps/marketplace/package.json, packages/apps/marketplace/src/pages/Marketplace/index.tsx, packages/apps/vault/package.json, packages/features/sales-escrows/modals/ConfirmEndSaleModal.tsx, packages/features/sales-escrows/modals/ManageDepositsModal.tsx, packages/features/sales-escrows/modals/ManageEscrows.tsx, packages/features/sales-escrows/modals/StartAuctionModal.tsx, packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/features/sales-escrows/modals/TransferTokens.tsx, packages/features/sales-escrows/modals/bidsReceivedTab.tsx, packages/features/sales-escrows/modals/bidsSentTab.tsx, packages/features/sales-escrows/modals/offersReceivedTab.tsx, packages/features/sales-escrows/modals/offersSentTab.tsx, packages/features/sales-escrows/package.json, packages/features/user-messages/package-lock.json, packages/features/user-messages/package.json, packages/features/user-messages/src/index.ts, tsconfig.json
• Replaced `sentBid.auction?.end_date > currentTimeInNanos` with `sentBid.auctionOpen` where necessary and refactored the code. 
• Implemented the isNftOwner props. Used also to make an extra check for Nft filtering (like in received bids) . 
• Implemented the preloader in the Tabs. 
📸
=> Fixes + preloader

packages/features/sales-escrows/modals/StartEscrowModal.tsx
- When sending an escrow (offer/bid/buy now), the fee is added to the total once, but the total shows 2x the fee since the canister will take another fee for the transaction.
- Note: the additional fee added to the total is for the second transaction from the deposit account to escrow.
=> ENG-1488 Fix Escrow Fees

packages/apps/marketplace/src/pages/Marketplace/index.tsx
=> ENG-1497-fixed

packages/features/sales-escrows/modals/ConfirmEndSaleModal.tsx, packages/features/sales-escrows/modals/ManageDepositsModal.tsx, packages/features/sales-escrows/modals/bidsReceivedTab.tsx, packages/features/sales-escrows/modals/bidsSentTab.tsx, packages/features/sales-escrows/modals/offersReceivedTab.tsx, packages/features/sales-escrows/modals/offersSentTab.tsx
• Fixed bigNumber 
• removed unused vars 
• cleaned layout of manageDeposit
📸
=> Eng-1497 align placeholder

packages/features/sales-escrows/modals/ConfirmEndSaleModal.tsx, packages/features/sales-escrows/modals/StartAuctionModal.tsx, packages/features/sales-escrows/modals/StartEscrowModal.tsx, packages/features/sales-escrows/modals/TransferTokens.tsx
• Added the balance 
• Added the error if the enteredAmount+fee is > balance (called every time the enteredValue changes) + disabled button
📷  ⚡
=> Eng 1526 add balance escrows

packages/apps/ledger/src/pages/Ledger/index.tsx, packages/features/components/src/Layout/index.tsx, packages/features/components/src/VLabel/index.test.jsx.txt, packages/features/components/src/VLabel/index.tsx, packages/features/components/src/index.ts
=> ENG-1531 removed Version from ledger
